apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: katib-ui-mapping
      prefix: /katib
      rewrite: ""
      service: katib-ui.kubeflow
  name: katib-ui
  namespace: kubeflow
  labels:
    app: vizier
    component: ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: ui
  selector:
    app: vizier
    component: ui
